# Site settings
title: Tomoya Matsuura
email: s2113241☆ms.geidai.ac.jp
description: "松浦知也のウェブページです。内容は未定です。"
baseurl: ""
url: "http://yourdomain.com"

# Build settings
markdown: kramdown
permalink: pretty
