hasCJKLanguage = true
DefaultContentLanguage = "ja"


baseURL = "http://matsuuratomoya.com/"
title = "Matsuura Tomoya"
enableMissingTranslationPlaceholders = false
publishDir = "docs"
theme = "tomoya"
[permalinks]
  blog = "/:section/:year-:month-:day/:filename/"
  info = "/:section/:year-:month-:day/:filename/"
[params]
  Twitter = "tomoya_nonymous"
  Facebook = "tomoya.matsuura.98"
  Github = "tomoyanonymous"
  Instagram = "tomoya_nonymous"
  Vimeo = "tomoyamatsuura"
  Soundcloud = "tomoya_matsuura"
  description = "松浦知也のWebサイトです。"
[[menu.main]]
  name = "about"
  url = "about"
  weight = 1
[[menu.main]]
  name = "info"
  url = "info"
  weight = 2
[[menu.main]]
  name = "works"
  url = "works"
  weight = 3
[[menu.main]]
  name = "blog"
  url = "blog"
  weight = 4
[[menu.main]]
  name = "contact"
  url = "contact"
  weight = 5

[languages]
[languages.ja]
weight = 1
languageCode = "ja"


[languages.en]
weight = 2
[languages.en.params]
description = "Website of Matsuura Tomoya."
